//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaPatchMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color title_name {
            get {
                return ((global::System.Drawing.Color)(this["title_name"]));
            }
            set {
                this["title_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color title_id {
            get {
                return ((global::System.Drawing.Color)(this["title_id"]));
            }
            set {
                this["title_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color hash {
            get {
                return ((global::System.Drawing.Color)(this["hash"]));
            }
            set {
                this["hash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color media_id {
            get {
                return ((global::System.Drawing.Color)(this["media_id"]));
            }
            set {
                this["media_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color patchHeader {
            get {
                return ((global::System.Drawing.Color)(this["patchHeader"]));
            }
            set {
                this["patchHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color name {
            get {
                return ((global::System.Drawing.Color)(this["name"]));
            }
            set {
                this["name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color desc {
            get {
                return ((global::System.Drawing.Color)(this["desc"]));
            }
            set {
                this["desc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color author {
            get {
                return ((global::System.Drawing.Color)(this["author"]));
            }
            set {
                this["author"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color is_enabled {
            get {
                return ((global::System.Drawing.Color)(this["is_enabled"]));
            }
            set {
                this["is_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color patchTypeHeader {
            get {
                return ((global::System.Drawing.Color)(this["patchTypeHeader"]));
            }
            set {
                this["patchTypeHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color address {
            get {
                return ((global::System.Drawing.Color)(this["address"]));
            }
            set {
                this["address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color value {
            get {
                return ((global::System.Drawing.Color)(this["value"]));
            }
            set {
                this["value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color title_nameInput {
            get {
                return ((global::System.Drawing.Color)(this["title_nameInput"]));
            }
            set {
                this["title_nameInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color title_idInput {
            get {
                return ((global::System.Drawing.Color)(this["title_idInput"]));
            }
            set {
                this["title_idInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color hashinput {
            get {
                return ((global::System.Drawing.Color)(this["hashinput"]));
            }
            set {
                this["hashinput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color media_idInput {
            get {
                return ((global::System.Drawing.Color)(this["media_idInput"]));
            }
            set {
                this["media_idInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color nameInput {
            get {
                return ((global::System.Drawing.Color)(this["nameInput"]));
            }
            set {
                this["nameInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color descInput {
            get {
                return ((global::System.Drawing.Color)(this["descInput"]));
            }
            set {
                this["descInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color authorInput {
            get {
                return ((global::System.Drawing.Color)(this["authorInput"]));
            }
            set {
                this["authorInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color addressInput {
            get {
                return ((global::System.Drawing.Color)(this["addressInput"]));
            }
            set {
                this["addressInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color valueInput {
            get {
                return ((global::System.Drawing.Color)(this["valueInput"]));
            }
            set {
                this["valueInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableDesc {
            get {
                return ((bool)(this["DisableDesc"]));
            }
            set {
                this["DisableDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WriteInfo {
            get {
                return ((bool)(this["WriteInfo"]));
            }
            set {
                this["WriteInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideValueConverter {
            get {
                return ((bool)(this["HideValueConverter"]));
            }
            set {
                this["HideValueConverter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDelete {
            get {
                return ((bool)(this["AutoDelete"]));
            }
            set {
                this["AutoDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableMessageBox {
            get {
                return ((bool)(this["DisableMessageBox"]));
            }
            set {
                this["DisableMessageBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColorDisabled {
            get {
                return ((bool)(this["ColorDisabled"]));
            }
            set {
                this["ColorDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultAuthors {
            get {
                return ((string)(this["DefaultAuthors"]));
            }
            set {
                this["DefaultAuthors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDefaultAuthors {
            get {
                return ((bool)(this["UseDefaultAuthors"]));
            }
            set {
                this["UseDefaultAuthors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsValueConverter {
            get {
                return ((bool)(this["IsValueConverter"]));
            }
            set {
                this["IsValueConverter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableAuthors {
            get {
                return ((bool)(this["DisableAuthors"]));
            }
            set {
                this["DisableAuthors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AddressMath {
            get {
                return ((int)(this["AddressMath"]));
            }
            set {
                this["AddressMath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color mainheadercolor1 {
            get {
                return ((global::System.Drawing.Color)(this["mainheadercolor1"]));
            }
            set {
                this["mainheadercolor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color mainheadercolor2 {
            get {
                return ((global::System.Drawing.Color)(this["mainheadercolor2"]));
            }
            set {
                this["mainheadercolor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color mainheadercolor3 {
            get {
                return ((global::System.Drawing.Color)(this["mainheadercolor3"]));
            }
            set {
                this["mainheadercolor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color mainheadercolor4 {
            get {
                return ((global::System.Drawing.Color)(this["mainheadercolor4"]));
            }
            set {
                this["mainheadercolor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color patchInfoColor1 {
            get {
                return ((global::System.Drawing.Color)(this["patchInfoColor1"]));
            }
            set {
                this["patchInfoColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color patchInfoColor2 {
            get {
                return ((global::System.Drawing.Color)(this["patchInfoColor2"]));
            }
            set {
                this["patchInfoColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color patchInfoColor3 {
            get {
                return ((global::System.Drawing.Color)(this["patchInfoColor3"]));
            }
            set {
                this["patchInfoColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PatchAddressColor1 {
            get {
                return ((global::System.Drawing.Color)(this["PatchAddressColor1"]));
            }
            set {
                this["PatchAddressColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PatchAddressColor2 {
            get {
                return ((global::System.Drawing.Color)(this["PatchAddressColor2"]));
            }
            set {
                this["PatchAddressColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PatchAddressColor3 {
            get {
                return ((global::System.Drawing.Color)(this["PatchAddressColor3"]));
            }
            set {
                this["PatchAddressColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PatchAddressColor4 {
            get {
                return ((global::System.Drawing.Color)(this["PatchAddressColor4"]));
            }
            set {
                this["PatchAddressColor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedPath {
            get {
                return ((string)(this["SavedPath"]));
            }
            set {
                this["SavedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SavePathBool {
            get {
                return ((bool)(this["SavePathBool"]));
            }
            set {
                this["SavePathBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PatchUseColor {
            get {
                return ((bool)(this["PatchUseColor"]));
            }
            set {
                this["PatchUseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PatchInfoUseColor {
            get {
                return ((bool)(this["PatchInfoUseColor"]));
            }
            set {
                this["PatchInfoUseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainUseColor {
            get {
                return ((bool)(this["MainUseColor"]));
            }
            set {
                this["MainUseColor"] = value;
            }
        }
    }
}
